### ISSUE TITLE
Please add documentation

### ISSUE THREAD

**Issue by retog** [fusepoolP3/p3-any23-transformer#1]
I don't find information on how to start and use.

**Comment by retog** [comment]
I still find no infomration on how to access the any23-transfomers. Accessing the started http server with "/" as uripath (http://localhsot:8080) will answer the request as if this was a transformer, but I don't see how this can be one, without me specifying which any23 extractor should be used.

**Comment by westei** [comment]
Why would you want to select a Any23 Transformer. The correct one is selected based on the Content-Type of the request. I have anyway created an example communication round trip for an other document. I will add this to the README. Maybe this makes things easier to understand.

**Comment by retog** [comment]
Ok, I see. Looking forward to a usage example. Can Any23 parameters (like any23.extraction.csv.field) be specified as query parameter?

**Comment by westei** [comment]
Currently not. However you can provide a Any23 configuration file as parameter when starting the transformer instance.

I do not think that the CSV functionality of Any23 is so useful because one can not configure the RDF its creates. The only thing it does is to use URIs in the headers of the CSV files as properties. However (e.g. it is not possible to define a row used as URIs ...). So what you get is a very generic RDF that will not be very useful in most use cases. 

IMO the most important feature of Any23 is the extraction of knowledge embedded in HTML files.

BTW: I updated the README already yesterday.
